
name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Web3dashboard

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js (optional, if no build tools, you can skip this)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        user_name: Binancewebonline
        user_email: Binancewebonline@outlook.com
